# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: red

# SEO
marketing:
  seo:
    site_type: LocalBusiness
    local_business_type: 'ProfessionalService'
    org_name: ''
    description: |
      严格守护你的网络安全。在卡瓦特网络安全公司，我们会提供根据您的需求量身定制的网络安全服务。
      从保护到审计，我们还提供培训、取证和定制安全软件。
    twitter: 'rouge_cravate'
  analytics:
    google_analytics: 'G-64YDD5310R'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: 'codeva-84l1iAxRFf'

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo-zh.png"
    button:
      enable: true
      text: "联络我们"
      url: "contact/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: |
      © {year} CravateRouge Ltd. All rights reserved.\
      CravateRouge Limited is a private limited company registered in Hong Kong SAR under the incorporation number 76292843.

# Localization
locale:
  date_format: '2 Jan, 2006'
  time_format: '15:04'
